openapi: 3.2.0
info:
  title: Cerebras Cloud Tcp Warming API
  version: 0.2.0
security:
- HTTPBearer: []
tags:
- name: Tcp Warming
paths:
  /v1/tcp_warming:
    get:
      operationId: tcp_warming_v1_tcp_warming_get
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Tcp Warming
      tags:
      - Tcp Warming
components:
  securitySchemes:
    HTTPBearer:
      scheme: bearer
      type: http
